### ISSUE TITLE
Gradle with 2.14 not working

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#1]
MacDietrich:xtext-reference-projects[master] dietrich$ scripts/greetings-gradle-2.14.sh
Fehler: Hauptklasse org.gradle.wrapper.GradleWrapperMain konnte nicht gefunden oder geladen werden

**Comment by cdietrich** [comment]
@kthoms this is fixed now correct?

**Comment by kthoms** [comment]
Right.
