### ISSUE TITLE
Reference projects for Xtext 2.16

### ISSUE THREAD

**Issue by szarnekow** [itemis/xtext-reference-projects#10]

**Comment by kthoms** [comment]
https://github.com/itemis/xtext-reference-projects/tree/master/domainmodel/2.16.0
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-gradle/2.16.0-J10
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-gradle/2.16.0-J9
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-gradle/2.16.0
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-maven/2.16.0-J10
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-maven/2.16.0
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-tycho/2.16.0-J10
https://github.com/itemis/xtext-reference-projects/tree/master/greetings-tycho/2.16.0

Build grün
https://travis-ci.org/itemis/xtext-reference-projects
