### ISSUE TITLE
Move Integ Tests (SWT Bot) to Java 11

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#129]
- update target platform to stable version with java 11 support
- run integ tests with java 11
- update tests to select Java 11 in Java version dropdowns
- adapt tests for new/changed gradle buildship foo https://github.com/itemis/xtext-reference-projects/compare/cd_201912?expand=1
- remove deletion of codemining stuff.

TODO: decide if java version for domain model needs increasing too

**Comment by ArneDeutsch** [comment]
Tests are moved to Java 11. Several causes for timeouts are fixed. Codemining stuff is not deleted any more.
