### ISSUE TITLE
Add CodeMining Test Cases to the Xtext examples

### ISSUE THREAD

**Issue by miklossy** [itemis/xtext-reference-projects#131]
The Xtext Arithmetics Example and the Xtext Domainmodel Example have been extended by CodeMiningTest test cases.

See: https://github.com/eclipse/xtext-eclipse/pull/1498

@ArneDeutsch Could you please integrate these test cases and make sure that they are also executed when building PHOTON and above? Thanks!

**Comment by cdietrich** [comment]
@miklossy i don’t understand: ref projects now already uses codemining

**Comment by miklossy** [comment]
Ok, I was not sure about that.

**Comment by miklossy** [comment]
@cdietrich: Thanks for your contribution https://github.com/itemis/xtext-reference-projects/pull/132
