### ISSUE TITLE
Domainmodel: Recreate for 2.16

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#15]
The domainmodel sample  for 2.16 should be recreated to reflect @miklossy s latest changes

**Comment by miklossy** [comment]
@cdietrich I could work on this issue. Please assign this ticket to me if you agree.

**Comment by cdietrich** [comment]
TODO see what tests say.
TODO maybe apply the manifest change regarding common.types.shared

**Comment by miklossy** [comment]
Test successful, I think we are done here.
