### ISSUE TITLE
Prepare 2.18 samples

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#48]

**Comment by miklossy** [comment]
The Domainmodel example UI test cases has to be extended by the highlighting test cases provided by the [Pull Request](https://github.com/eclipse/xtext-eclipse/pull/1014) .

**Comment by miklossy** [comment]
The duplicate entry in maven clean plugin config should also be removed, see [Pull Request](https://github.com/eclipse/xtext-eclipse/pull/1021).

**Comment by cdietrich** [comment]
Done
