### ISSUE TITLE
[J10] add Java 10 to matrix once available

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#5]
- add Java 10 to matrix once available
- add a Test Xtext 2.14 + J10

**Comment by cdietrich** [comment]
Java 10 is out now. Xtext is still waiting for new mavenized jdt and tycho

**Comment by kthoms** [comment]
Solved with https://github.com/itemis/xtext-reference-projects/commit/6411c64e18767cd9194637801761a224b9d519c8
