### ISSUE TITLE
Some reference projects fail due to signing issue Xtext#1231

### ISSUE THREAD

**Issue by kthoms** [itemis/xtext-reference-projects#8]
Some of the projects fail with the known signing issue eclipse/xtext#1231

- greetings-maven-2.14-J10.sh  (JDK 10)
- greetings-maven-2.12.sh (JDK 8)
- greetings-maven-2.13.sh (JDK 8)
- greetings-maven-2.14.sh (JDK 8, 9, 10)
- greetings-maven-2.14-J10.sh  (JDK 10)

**Comment by cdietrich** [comment]
The projects have already a workaround in please. This one needs to be extended for using NOT emf 215
