### ISSUE TITLE
Close all console views after test execution

### ISSUE THREAD

**Issue by miklossy** [itemis/xtext-reference-projects#85]
As discussed with @cdietrich , the SWTBot integration test cases should close all consoles in their teardown methods to prevent that they will be picked up by subsequent test cases.

https://github.com/itemis/xtext-reference-projects/blob/master/integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/ConsoleViewAPI.java#L60

**Comment by cdietrich** [comment]
gonna workaround these and others problems using travis_retry

**Comment by miklossy** [comment]
For the short term the woraround is acceptable for me, but for the long term I would like to have this implemented in the tests before/after phase.
